properties([
  parameters([
    string(name: 'YOAST_TAG', defaultValue: '15.0', description: 'The target environment', ),
	string(name: 'README_FILE', defaultValue: 'readme.txt', description: 'The readme file name', ),
	string(name: 'FOLDER_NAME', defaultValue: 'wordpress-seo', description: 'what is the folder name', ),
	string(name: 'ChanglogPostid', defaultValue: '1292114', description: 'POST ID ON YOAST.COM OF CHANGELOG', )
   ])
])
node( 'docker-agent' ) {
	checkout scm
	docker.withServer( 'tcp://172.17.0.1:2375' ) {
		stage('build') {
			def ubuntu = docker.image( 'yoastseo/docker-php-composer-node' )
			ubuntu.pull()
			ubuntu.inside( '-e SC_ATTR="yoast-seo"  ' ) { 
				/*
				sh 'echo "Will deploy to ${DEPLOY_ENV}"'
				*/ 
				sh 'echo "SC_ATTR is set to  ${SC_ATTR} " '
				sh 'mkdir ~/.ssh'
				sh 'ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts'
				sh 'pwd'
				sh 'ls -al config/jenkins/'
				catchError {
					sshagent (credentials: ['Jenkins-CI']) {
						sh 'bash config/jenkins/test.cmd'
					}
				}
				
			}
		}
	}
}