pipeline {
    agent { docker { image 'ubuntu' } }
    stages {
        stage('build') {
			steps {
				sh 'pwd'
				sh 'ls -al config/jenkins/'
				
				sh 'ssh -o StrictHostKeyChecking=no -l pi 10.0.10.10 uname -a'
				
				
				sh 'config/jenkins/test.cmd'
            }
        }
    }
}
